name: Deploy To Google Cloud Run 
# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
  deployToBeta:     
    runs-on: ubuntu-latest
    needs: build
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7] 
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with: 
          service_account_key: ${{secrets.RUN_SA_KEY}}
          
      - name: Login to Docker Registry
        run: |
          gcloud auth configure-docker --quiet
      
      - name: Checkout repository
        uses: actions/checkout@v2
      
      
        
      # Runs a set of commands using the runners shell
      # RUN_PROJECT: It is the name of project in the GCP.
      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{secrets.RUN_PROJECT}}/demo-image830 .
      
      # vault kv get -address="https://vault.sirpi.co.in" -field=env kv/projects/herokutest > .env
      # vault kv get -address="https://vault.sirpi.co.in" -field=ignore kv/projects/herokutest > .gitignore
      - name: Push Docker image
        run: |
          docker push gcr.io/${{secrets.RUN_PROJECT}}/demo-image830
      
      - name: Deploy Docker image
        run: |
          gcloud run deploy demo-image830 --project=${{secrets.RUN_PROJECT}} --image gcr.io/${{secrets.RUN_PROJECT}}/demo-image830 --region us-central1 --allow-unauthenticated --platform managed
   
